from __future__ import annotations

import subprocess
from pathlib import Path

import check_architecture
import generate_db_schema
import validate
from lib import DOCS_ROOT, REPO_ROOT, today_string, write_text


QUALITY_PATH = DOCS_ROOT / "QUALITY_SCORE.md"
PR_BODY_PATH = DOCS_ROOT / "generated" / "doc-garden-pr.md"


def metric_score(passed: bool, fallback: int = 2) -> int:
    return 5 if passed else fallback


def render_quality(validate_result: dict, architecture_result: dict) -> str:
    checks = {check["name"]: check for check in validate_result["checks"]}
    architecture_ok = architecture_result["ok"]
    topology_ok = (
        checks["required_layout"]["ok"]
        and checks["frontmatter"]["ok"]
        and checks["local_links"]["ok"]
        and checks["archive_truth_ban"]["ok"]
    )
    command_ok = checks["command_sync"]["ok"]
    generated_ok = generate_db_schema.is_current()
    clarity_ok = checks["workflow_files"]["ok"] and checks["agents_length"]["ok"] and command_ok

    metrics = [
        ("Documentation topology", metric_score(topology_ok), "Layout, frontmatter, links, and truth-source boundaries"),
        ("Command/source drift", metric_score(command_ok), "Shared command surface matches xuejian/package.json"),
        ("Architecture drift", metric_score(architecture_ok, 1), "Path-level TypeScript and Rust boundaries"),
        ("Generated artifact freshness", metric_score(generated_ok), "Generated DB schema matches migrations"),
        ("Test-and-check clarity", metric_score(clarity_ok, 3), "Workflows and short agent entrypoints remain usable"),
    ]

    failed_checks = [
        f"- `{check['name']}`: {'; '.join(check['details'])}"
        for check in validate_result["checks"]
        if not check["ok"]
    ]
    failed_checks.extend(
        f"- `{check['name']}`: {'; '.join(check['details'])}"
        for check in architecture_result["checks"]
        if not check["ok"]
    )

    lines = [
        "---",
        "title: Quality Score",
        "status: active",
        "owner: platform",
        f"last_reviewed: {today_string()}",
        "canonical: true",
        "---",
        "",
        "# QUALITY_SCORE",
        "",
        f"Last garden run: `{today_string()}`",
        "",
        "| Metric | Score | Notes |",
        "| --- | --- | --- |",
    ]
    for name, score, notes in metrics:
        lines.append(f"| {name} | {score} | {notes} |")

    lines.extend(["", "## Signals"])
    if failed_checks:
        lines.extend(failed_checks)
    else:
        lines.append("- All current documentation and architecture checks passed.")

    lines.extend(
        [
            "",
            "## Update Policy",
            "",
            "- Generated by `python scripts/docs/garden.py`.",
            "- When a metric drops, create or update an entry in `docs/exec-plans/tech-debt-tracker.md`.",
        ]
    )
    lines.append("")
    return "\n".join(lines)


def render_pr_body(validate_result: dict, architecture_result: dict) -> str:
    failed = [
        f"- `{check['name']}`: {'; '.join(check['details'])}"
        for check in validate_result["checks"] + architecture_result["checks"]
        if not check["ok"]
    ]
    lines = [
        "# Weekly doc garden",
        "",
        "- Refreshed `docs/generated/db-schema.md` from current migrations.",
        "- Refreshed `docs/QUALITY_SCORE.md` from current repository checks.",
    ]
    if failed:
        lines.extend(["", "## Follow-up", ""])
        lines.extend(failed)
    else:
        lines.extend(["", "## Follow-up", "", "- No new drift was detected by the current mechanical checks."])
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    generate_db_schema.write_schema()
    validate_result = validate.run_checks()
    architecture_result = check_architecture.run_checks()

    write_text(QUALITY_PATH, render_quality(validate_result, architecture_result))
    write_text(PR_BODY_PATH, render_pr_body(validate_result, architecture_result))

    changed = subprocess.run(
        ["git", "status", "--short", "--", str(DOCS_ROOT)],
        cwd=REPO_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if changed.stdout.strip():
        print(changed.stdout.rstrip())
    else:
        print("No documentation changes detected.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
