"""Shared constants for the Knowledge QA RAG pipeline."""
from __future__ import annotations

RETRIEVAL_CANDIDATE_LIMIT = 24
MAX_PASSAGES = 8
MAX_PASSAGE_CHARS = 800
MAX_TOTAL_CONTEXT_CHARS = 5_000
MAX_CITATION_CHARS = 160
MAX_PARENT_CONTEXT_CHARS = 3_000
MAX_EXPANDED_CONTEXT_CHARS = 500
MAX_SECTION_HEADING_CHARS = 160
MODEL_TIMEOUT_SECONDS = 45
MODEL_MAX_TOKENS = 900
RECENT_MESSAGES_LIMIT = 4
REWRITE_SHORT_QUERY_CHARS = 10
REWRITE_QUERY_MAX_CHARS = 120
SECOND_RETRIEVAL_QUERY_MAX_CHARS = 120
RERANK_LLM_MAX_CHUNKS = 6
RELEVANCE_GATE_MIN_SCORE = 0.25
RELEVANCE_GATE_FALLBACK_SCORE = 0.016
RERANK_MODE_ENV = "XUEJIAN_KNOWLEDGE_QA_RERANK_MODE"
ALLOWED_RERANK_MODES = {"disabled", "local_rule", "llm_provider"}
REWRITE_REFERENTIAL_TERMS = ("它", "这个", "那个", "上面", "以上", "之前", "其", "该")
SHORT_FOLLOW_UP_TERMS = ("优缺点", "区别", "总结", "步骤", "方法", "原理", "怎么做", "是什么")
